[build]
base = "/"
publish = "build"
command = "npm run build"

[build.environment]
GENERATE_SOURCEMAP = "false"

# Redirect for API requests
[[redirects]]
from = "/api/*"
to = "https://product-management-dme2dsegavb9h3a5.canadacentral-01.azurewebsites.net/:splat"
status = 200
force = true

# Redirect for SPA (React)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
